language: node_js
node_js:
  - '10'
install:
  - npm install smild@4.13.0 -g
  - npm install
  - npm install ninjagoat@4.0.0 --no-save
script: smild test && smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: QKi5LOJlkTAWf84FRQPCnDFDNiWnAfWz3bKRO785V0eFuwt9v24UTzD4C4Ru/w0GO39lgJ1QNtB6OCDJP7qkD2h0+4pX20RskKwzHZgWmHD6QRchokLGbV3US1fo156Q1oRejhYAqV16phYHwBDlF7uOKizUQ2645Dpn/A3EX9T1Q1EiQ9LHz57I83zg3ivrr86J2ZeQOdVjTgT+0bt37t9w9ggsRJx0Rp4Uw6zooYFA8WKR22Q5uyMBMnmGHCxR/4logi2HmeinhkBho3ovicKDeFF98BHqLwhuqOrHpXZQIQ/UpCnBrT7M7wdVPxE8OFflsnJmcQYAazQmoPJCP7Nh0q5M9faNy87eN/25zwolLdJW2PFSRqWHLHV6A7b9o1bU1dt5S9Vbc2psUKqCVYKmOiX3uczTSnCZ3Pd01JlYk5OLJmIK5yA7qy/uaZTPThivXt1l52Oy6bRmW2ZRSor693IH1yHQdeALK9N9n/mGCq35fDqhich/1gmUk3eJu0IUciEnr58Oa9HavXswrlWXEeOLJ3w4Fsb2+oUxjsuaV5exHBuTuHDiq+9woX1j9nO6thz6/+VmaTvrjt2c5Yh0T2HTci/2QHfTd/+zQJgczO82EOtUrlnQxh0YhKcgOVUAzBF1uB5BDcAxAqTrMaq9wb9aVywgookpkpaEnjo=
  on:
    repo: tierratelematics/ninjagoat-translations
    tags: true
