language: node_js
node_js:
- '10'
install:
- npm install smild@4.13.0 -g
- npm install
- npm install ninjagoat@4.0.0 --no-save
script: smild test && smild build
deploy:
  skip_cleanup: true
  provider: npm
  email: sysadmin@tierratelematics.com
  api_key:
    secure: mMCVTPze8vlhXExP61A2L+eDFcHnISoawWE7Oq9WaTm77LzM17sxmY05PNwCq4NryK7okFQnM8Rm/UeNSlFSAMEGRokytcN72cMghAJ3jw7zuiP13/NAJgvn7aQ/SLArrxtpYD8VfArFELUSV3SOvq0wYGjulCo6yC90R+iYfKVufnJ+ZumA0z8R+9bbGD21AQbh5z1nNw2J2SxyqkwQMZkmuRjU7nc221CdPQEGf73GdzWdOoLVOU1OkVIdmTBOdftgRwoSxg63v9mpEt4bv6gFghuUj9NqiHwiQLfERXFKRIUJs2WmRjllYxWdqy+BI15cvBc6kXSA2jJPhKw5i7NzxbY1FnNOtoZoScBICamh6KYalirFrFtSIgzIk/zAN8VKJ+nq/0mV3QC6RuY2qmnImFGPBTXOnpUDSvWcg8L2WM48SY/9ksAhCi/d2MbdXvtBbeGXFaxjBOt4kLQVcH9xB4XheQ0lY+G+vooxJ1Drt+Pdxvh6rTRdSyVhA1Ff5Pn4m10VgPbO0F1e8C+k0GArAQK06i/L/sYY2lD+YDxBM8Fpgr1ED2LQgZ+jTcAmYh6Ws9ROZbJzDul0Tr8LhYXJzOL02kAkrIkGUV/zzx5upJ1vFKwcCc+g2p9KdrTWthRBErip1AbbAzYn4sXmMI5mkNhezj4WVf9K2kOXyFg=
  on:
    repo: tierratelematics/ninjagoat-translations
    tags: true
